version: '2'
services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app
    ports:
     - "${APP_EXTERNAL_PORT}:${APP_PORT}"
  mysql:
    extends:
        file: docker-compose.base.yml
        service: mysql
    restart: always
    ports:
     - "${DB_EXTERNAL_PORT}:${DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
    ports:
     - "${REDIS_EXTERNAL_PORT}:${REDIS_PORT}"
    command: "--port ${REDIS_PORT}"
networks:
  sdnet:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"
  redisdata:
    driver: "local"
